### PR TITLE
Migrate to sci.lang.Type

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Comment by borkdude** [comment]
@frenchy64 The only thing failing is `fancy-explain-test`, but I can't see why. The output looks like what's expected.

**Comment by borkdude** [comment]
I recommend running the tests with 0.8.3 just published a few days ago.

**Comment by frenchy64** [comment]
I found 0.8.156, but no 0.8.3.

**Comment by borkdude** [comment]
Sorry, 0.8.156 is the one :) I switched to major.minor.release

**Pull request merged**
